spring:
  datasource:
    url: jdbc:mysql://49.234.13.45:3306/work1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      additional-exclude: static/**
      additional-paths: src/main/java
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
